; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
BrandingText "DelphiTeacher版权所有(C)2004-2026"
!define PRODUCT_NAME "OpenClawDesktop客户端"
!define PRODUCT_DIRNAME "OpenClawDesktop"
!define PRODUCT_EXENAME "OpenClawDesktop"


!define PRODUCT_TYPE "Alpha"
!define PRODUCT_VERSION "Ver: 1.0.0(${PRODUCT_TYPE})"
!define PRODUCT_PUBLISHER "DelphiTeacher"
!define PRODUCT_WEB_SITE "http://www.orangeui.cn/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\${PRODUCT_EXENAME}.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"


; MUI 1.67 compatible ------
!include "MUI.nsh"
!include "Sections.nsh"
!include "FileFunc.nsh"
!include "${NSISDIR}\Include\LogicLib.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON ".\PublicFiles\pic\orange-install.ico"
!define MUI_UNICON ".\PublicFiles\pic\orange-uninstall.ico"
!define MUI_WELCOMEFINISHPAGE_BITMAP ".\PublicFiles\pic\ORANGE.bmp"
!define MUI_HEADERIMAGE_RIGHT ".\PublicFiles\pic\ORANGE.bmp"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE ".\PublicFiles\License.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_COMPONENTS

!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_SHOWREADME
!define MUI_FINISHPAGE_RUN "$INSTDIR\${PRODUCT_EXENAME}.exe"
!define MUI_FINISHPAGE_RUN_NOTCHECKED
!insertmacro MUI_PAGE_FINISH


; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"
!insertmacro DriveSpace


; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "${PRODUCT_EXENAME} Install.exe"
InstallDir "$PROGRAMFILES\${PRODUCT_DIRNAME}"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show
Function .onInit
  StrCpy $R1 "D:\${PRODUCT_DIRNAME}\"
  ${DriveSpace} $R1 "/D=F /S=G" $R0
  ${If} $R0 = null
    StrCpy $R1 "D:\${PRODUCT_DIRNAME}\"
    ${EndIf}
    StrCpy $INSTDIR "$R1";
FunctionEnd
  

Section "主程序文件" SEC01

  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File ".\PublicFiles\License.txt"
  CreateDirectory "$SMPROGRAMS\${PRODUCT_DIRNAME}\"
  File "D:\OpenClawCode\desktopclient\Source\Win32\Debug\sk4d.dll"
  File "D:\OpenClawCode\desktopclient\Source\Win32\Debug\WebView2Loader.dll"
  File "D:\OpenClawCode\desktopclient\Source\Win32\Debug\OpenClawDesktop.exe"
  File "D:\OpenClawCode\desktopclient\Source\Win32\Debug\channel.json"
  File "D:\OpenClawCode\desktopclient\Source\Win32\Debug\models.json"
  File /r "D:\OpenClawCode\desktopclient\Source\Win32\Debug\provider"
  File /r "D:\OpenClawCode\desktopclient\Source\Win32\Debug\node"
  File /r "D:\OpenClawCode\desktopclient\Source\Win32\Debug\icons"
  File /r "D:\OpenClawCode\desktopclient\Source\Win32\Debug\openclaw"
  

  CreateShortCut "$DESKTOP\${PRODUCT_NAME}.lnk" "$INSTDIR\${PRODUCT_EXENAME}.exe"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_DIRNAME}\${PRODUCT_EXENAME}.lnk" "$INSTDIR\${PRODUCT_EXENAME}.exe"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_DIRNAME}\Uninstall.lnk" "$INSTDIR\uninst.exe"  
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "http://www.nwh.cn"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_DIRNAME}\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_DIRNAME}\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\${PRODUCT_EXENAME}.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\${PRODUCT_EXENAME}.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  SetShellVarContext all
  
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\License.txt"

  Delete "$DESKTOP\${PRODUCT_EXENAME}.lnk"  
  RMDir /r "$SMPROGRAMS\${PRODUCT_DIRNAME}\"

  RMDir /r "$INSTDIR\"
 
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd