//convert pas to utf8 by ¥
unit FileManageRestService;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding services unit name 
// to it. Eg.
//
//     uses ...,kbmMWServer,YourServiceUnitName;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance.
// This can be done by registering the traditional way, or by using auto registration.
// 
// Traditional registration
// ------------------------
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 
// 
// Auto registration
// -----------------
// Make sure that your service class is tagged with the [kbmMW_Service] attribute.
// Then auto register all tagged services:
// ..
//    kbmMWServer1.AutoRegisterServices;
// 
// -----------------------------------------------



{$I kbmMW.inc}

interface

uses
  SysUtils,
{$ifdef LEVEL6}
  Variants,
{$else}
  Forms,
{$endif}
  Classes,
  DateUtils,
  Math,
  System.Generics.Collections,


  IniFiles,
  XSuperObject,
  XSuperJson,


//  Forms,
  StrUtils,

//  uDateCommon,
//  uCommonUtils,
  uDataSetToJson,
//  uBaseDBHelper,
//  uUniDBHelper,
  uFuncCommon,
  uFileCommon,
//  uLang,

  kbmMWCustomHTTPService,
  FileIndyHttpServerModule,
  uOpenPlatformServerManager,
  kbmMWHTTPUtils,
  kbmMWCustomHTTPSmartService,
//  kbmMWCustomHTTPService,
//  FileHttpService,
  kbmMWFilePool,

//  uGetExcelFileContent,

  IdMessageCoder,
  IdMessageCoderMIME,
  System.NetEncoding,


  uTableCommonRestCenter,
  TableCommonRestService,


  kbmMWSecurity,
  kbmMWServer,
  kbmMWServiceUtils,
  kbmMWGlobal,
  kbmMWCustomSmartService
   ,kbmMWRTTI
   ,kbmMWSmartServiceUtils;





type
  [kbmMW_Service('name:filemanage, flags:[listed]')]
  [kbmMW_Rest('path:/filemanage')]
  // Access to the service can be limited using the [kbmMW_Auth..] attribute.
  // [kbmMW_Auth('role:[SomeRole,SomeOtherRole], grant:true')]

  TsrvFileManageRestService = class(TkbmMWCustomHTTPSmartService)//TkbmMWCustomSmartService)
     { Private declarations }
  protected
     { Protected declarations }
  public
     { Public declarations }
     // HelloWorld function callable from both a regular client,
     // due to the optional [kbmMW_Method] attribute,
     // and from a REST client due to the optional [kbmMW_Rest] attribute.
     // The access path to the function from a REST client (like a browser)+
     // is in this case relative to the services path.
     // In this example: http://.../xalionservice/helloworld
     // Access to the function can be limited using the [kbmMW_Auth..] attribute.
     // [kbmMW_Auth('role:[SomeRole,SomeOtherRole], grant:true')]

     //http://127.0.0.1:10000/filemanage/helloworld
     //http://127.0.0.1:10000/filemanage/echostring/abc
     //http://127.0.0.1:10000/filemanage/cal/addnumbers?arg1=1&arg2=2
     //http://127.0.0.1:10000/filemanage/send_register_captcha?phone=18957901025
     //http://127.0.0.1:10000/filemanage/register_user?appid=1001&phone=18957901025&filemanage=2721&name=ggggcexx&password=123456&repassword=123456


     //加了[kbmMW_Method]属性的方法才会被访问到
     //[kbmMW_Rest].method表示访问所使用的方法
     //[kbmMW_Rest].path表示访问的路径,可以有别名
     [kbmMW_Rest('method:get, path:helloworld')]
     [kbmMW_Method]
     function HelloWorld:String;


     //回应输入的串
     [kbmMW_Method('EchoString')]
     [kbmMW_Rest('method:get, path: [ "echostring/{AString}","myechostring/{AString}" ]')]
     [kbmMW_Auth('role:[SomeRole,SomeOtherRole], grant:true')]
     function EchoString([kbmMW_Rest('value: "{AString}"')] const AString:String):String;


     [kbmMW_Method]
     [kbmMW_Rest('method:get, path: "cal/addnumbers"')]
     function AddNumbers([kbmMW_Rest('value: "$arg1", required: false')] const AValue1:Integer;
                         [kbmMW_Rest('value: "$arg2", required: false')] const AValue2:Integer;
                         [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):Integer;

  public

    //判断文件是否存在
    [kbmMW_Method]
    [kbmMW_Rest('method:get, path: "check_file_exists"')]
    function CheckFileExists([kbmMW_Rest('value: "$appid", required: false')] const AAppID:Integer;
                              [kbmMW_Rest('value: "$file_path", required: false')] const AFilePath:String;
                              [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):String;

  public

    //上传文件
    [kbmMW_Method]
    [kbmMW_Rest('method:post, path: "upload"')]
    function Upload([kbmMW_Rest('value: "$appid", required: false')] const AAppID:String;
                    [kbmMW_Rest('value: "$key", required: false')] const key:String;
                    [kbmMW_Rest('value: "$filedir", required: false')] const AFileDir:String;
                    [kbmMW_Rest('value: "$filename", required: false')] const AFileName:String;
                    [kbmMW_Rest('value: "$fileext", required: false')] AFileExt:String;
                    [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):String;

    //上传文件
    [kbmMW_Method]
    [kbmMW_Rest('method:post, path: "upload_file"')]
    function upload_file(
                    [kbmMW_Rest('value: "$key", required: false')] const key:String;
                    [kbmMW_Rest('value: "$filedir", required: false')] AFileDir:String;
                    [kbmMW_Rest('value: "$filename", required: false')] const AFileName:String;
                    [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):String;

//    //上传文件
//    [kbmMW_Method]
//    [kbmMW_Rest('method:post, path: "upload"')]
//    function Upload([kbmMW_Rest('value: "$appid", required: false')] const AAppID:String;
//                              [kbmMW_Rest('value: "$filedir", required: false')] const AFileDir:String;
//                              [kbmMW_Rest('value: "$filename", required: false')] const AFileName:String;
//                              [kbmMW_Rest('value: "$fileext", required: false')] AFileExt:String;
//                              [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):String;


//    //下载文件
//    [kbmMW_Method]
//    [kbmMW_Rest('method:get, path: "download"')]
//    function Upload([kbmMW_Rest('value: "$appid", required: false')] const AAppID:String;
//                              [kbmMW_Rest('value: "$filepath", required: false')] const AFileDir:String;
//                              [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):String;
//

    public
      //上传Excel文件，将文件保存到临时目录，返回它有多少个表单,拆分成一个个工作表
      //上传文件
      [kbmMW_Method]
      [kbmMW_Rest('method:post, path: "format_excel_file"')]
      function format_excel_file(
//                      [kbmMW_Rest('value: "$key", required: false')] const key:String;
//                      [kbmMW_Rest('value: "$filedir", required: false')] AFileDir:String;
//                      [kbmMW_Rest('value: "$filename", required: false')] const AFileName:String;
                      [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):String;


    //上传文件
    [kbmMW_Method]
    [kbmMW_Rest('method:post, path: "upload_form"')]
    function Upload_form(//[kbmMW_Rest('value: "$appid", required: false')] const AAppID:String;
                    [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):String;


    public
      function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
  end;





  TFileManageServiceModule=class(TKbmMWServiceModule)
  private
//    WWWRootDirList:TStringList;
  public
//    kbmMWFilePool1:TkbmMWFilePool;
    dmFileIndyHttpServer:TdmFileIndyHttpServer;
  public
    constructor Create;override;
    destructor Destroy;override;
  public
    procedure Init;override;
    //准备启动
    function DoPrepareStart(var AError:String):Boolean;override;
    //准备停止
    function DoPrepareStop:Boolean;override;

    procedure AddWWWRootDir(AWWWRootDir:String);
    //启动后
    procedure DoAfterStart; override;
  end;






var
  //服务模块
  FileManageServiceModule:TFileManageServiceModule;

implementation


uses
  kbmMWExceptions;






{$R *.dfm}


// Service definitions.
//---------------------


function TsrvFileManageRestService.AddNumbers(const AValue1, AValue2: Integer;
  const ARemoteLocation: String): Integer;
begin
  Result:=AValue1+AValue2;
end;

function TsrvFileManageRestService.CheckFileExists(const AAppID: Integer;
  const AFilePath, ARemoteLocation: String): String;
var
  ACode:Integer;
  ADesc:String;
  ADataJson:ISuperObject;
begin

  ACode:=FAIL;
  ADesc:='';
  ADataJson:=nil;


  if AAppID=0 then
  begin
    ADesc:=('AppID不能为空');
    Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
    Exit;
  end;

  if Trim(AFilePath)='' then
  begin
    ADesc:=('文件路径不能为空');
    Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
    Exit;
  end;



  try


    //判断文件是否存在
    if FileExists(FileManageServiceModule.dmFileIndyHttpServer.WWWRootDir+AFilePath) then
    begin

        //成功
        ADesc:=('文件存在');
        ACode:=SUCC;

    end
    else
    begin
        //文件不存在
        ADesc:=('文件不存在');
    end;


  finally
    Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
  end;

end;


//function TsrvFileManageRestService.Download: String;
////var
////  vl:TkbmMWHTTPCustomValues;
//////  s,xsxm,sfzh:string;
////
////  p:Tbytes;
//var
//  LFilename: string;
//  LPathname: string;
//
//  AAppID:String;
//  AFileDir:String;
//  AFileName:String;
//  AFileExt:String;
//  AContentType:String;
//
//  ARemoteFilePath:String;
//
//  ACode:Integer;
//  ADesc:String;
//  ADataJson:ISuperObject;
//
////  AMimeDecoder: TIdMessageDecoder;
////  ABodyStream:TMemoryStream;
////  AIdHeaderList:TIdHeaderList;
////  msgEnd:Boolean;
////
////  ANetHttpClient:TNetHttpClient;
////  AUrl:String;
//
//  qv:TkbmMWHTTPQueryValues;
//begin
////  vl:=TkbmMWHTTPQueryValues.Create;
////  try
//
//
//
////     p:= RequestStream.SaveToBytes;
////
////     vl.AsString:= TEncoding.ASCII.GetString(p);
//
//
//
////     xsxm:= vl.ValueByName['xsxm'];
////     sfzh:=vl.ValueByName['sfzh'];
////
////     // 这里就可以向数据库里面操作了
////
////       result:='姓名:'+xsxm+'      身份证号'+sfzh;
//
//
//
//
//      //  uBaseLog.HandleException(nil,'TdmFileIndyHttpServer.IdHTTPServerCommandGet Begin');
//      //  uBaseLog.HandleException(nil,'TdmFileIndyHttpServer.IdHTTPServerCommandGet Document='+ARequestInfo.Document);
//      //  uBaseLog.HandleException(nil,'TdmFileIndyHttpServer.IdHTTPServerCommandGet Params='+ARequestInfo.Params.Text);
//
//
//        //浏览器请求http://127.0.0.1:8008/index.html?a=1&b=2
//        //ARequestInfo.Document  返回    /index.html
//        //ARequestInfo.QueryParams 返回  a=1b=2
//        //ARequestInfo.Params.Values['name']   接收get,post过来的数据
//        ////webserver发文件
////        LFilename := ARequestInfo.Document;
////
////
////        //浏览器请求http://127.0.0.1:8008/upload?
////        //appid=1002&filename=aaa.jpg&filedir=goods_pic&fileext=.jpg
////        if SameText(LFilename,'/upload') then
////        begin
//
////                 // Execute method.
////                 qv:=TkbmMWHTTPQueryValues.Create;
////                 try
//////                    if length(FArgs)>2 then
////                       qv.AsString:=FUrlParams;//FArgs[2];
//////                    Result:=CallMethod(m,pm,sl,qv,AClientIdent,AArgs,ARequestStream,AResult);
//////
//////                    // Check if to set mimeType and charSet respomse properties.
//////                    if (AService is TkbmMWCustomHTTPService) then
//////                    begin
//////                         s:=attrr.ResponseMimeType;
//////                         if s<>'' then
//////                            TkbmMWCustomHTTPService(AService).SetResponseMimeType(s);
//////                         s:=attrr.ResponseCharSet;
//////                         if s<>'' then
//////                            TkbmMWCustomHTTPService(AService).SetResponseCharset(s);
//////                    end;
//////                    if attrr.AnonymousResult then
//////                       AFlags:=AFlags+[mwssmfAnonymousResult];
//////                    if attrr.PrettyResult then
//////                       AFlags:=AFlags+[mwssmfPrettyResult];
////
////                    //需要验证APPKey,不然会受攻击
////                    AAppID:=qv.ValueByName['appid'];//ARequestInfo.Params.Values['appid'];
////                    AFileDir:=qv.ValueByName['filedir'];//ARequestInfo.Params.Values['filedir'];
////
////                    //filename参数表示保存的文件名,有后缀,但是这个文件名我们不使用
////                    AFileName:=qv.ValueByName['filename'];//ARequestInfo.Params.Values['filename'];
////                    AFileExt:=qv.ValueByName['fileext'];//ARequestInfo.Params.Values['fileext'];
////
////                 finally
////                    qv.Free;
////                 end;
//
//
//
//
//
//                //上传文件
//                ACode:=FAIL;
//                ADesc:='';
//                ADataJson:=nil;
//
//                try
//
//
////                      //需要验证APPKey,不然会受攻击
////                      AAppID:=ARequestInfo.Params.Values['appid'];
////                      AFileDir:=ARequestInfo.Params.Values['filedir'];
////
////                      //filename参数表示保存的文件名,有后缀,但是这个文件名我们不使用
////                      AFileName:=ARequestInfo.Params.Values['filename'];
////                      AFileExt:=ARequestInfo.Params.Values['fileext'];
//                      if AFileExt='' then
//                      begin
//                        AFileExt:=ExtractFileExt(AFileName);
//                      end;
//
//
//
//
//                      ARemoteFilePath:='';
//                      if ProcessUploadFile(ExtractFilePath(Application.ExeName),
//                                           AAppID,
//                                           AFileExt,
//                                           AFileDir,
//                                           RequestStream,
//                                           ARemoteFilePath,
//                                           ACode,
//                                           ADesc) then
//                      begin
//                        //上传成功
//                      end;
//
//                  finally
//                      //返回
//                      ADataJson:=TSuperObject.Create;
//                      ADataJson.S['RemoteFilePath']:=ARemoteFilePath;
//                      ADataJson.S['Url']:=ReplaceStr(ARemoteFilePath,'\','/');
////                      AResponseInfo.ContentText
//                      Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
//                  end;
//
//
////        end
////        else if SameText(LFilename,'/plupload') then
////        begin
////                //解决plupload这个JS图片上传控件的跨域问题
////                //OPTIONS命令
////                AResponseInfo.CustomHeaders.Values['Access-Control-Allow-Origin']:='*';
////
////                ACode:=FAIL;
////                ADesc:='';
////                ADataJson:=nil;
////                try
////                    //需要验证APPKey,不然会受攻击
////                    AAppID:=ARequestInfo.Params.Values['appid'];
////                    AFileDir:=ARequestInfo.Params.Values['filedir'];
////
////                    if (Trim(AAppID)='') then
////                    begin
////                      ADesc:=('AppID不能为空');
////                      Exit;
////                    end;
////                    if (Trim(AFileDir)='') then
////                    begin
////                      ADesc:=('FileDir不能为空');
////                      Exit;
////                    end;
////
////
////                    //给plupload这个JS文件上传控件做的接口
////                    if ARequestInfo.PostStream<>nil then
////                    begin
////                        ARequestInfo.PostStream.Position:=0;
////                        //保存到本地测试
////                //        TMemoryStream(ARequestInfo.PostStream).SaveToFile('D:\post.txt');
////
////
////                        //------WebKitFormBoundaryOWWn6zTHJMweb4kk
////                        //Content-Disposition: form-data; name="name"
////                        //
////                        //9A0B3A9D240F2C52CCFA82780B1BB1A5.jpg
////                        //------WebKitFormBoundaryOWWn6zTHJMweb4kk
////
////              //Content-Disposition: form-data; name="file"; filename="9A0B3A9D240F2C52CCFA82780B1BB1A5.jpg"
////                        //Content-Type: image/jpeg
////                        AMimeDecoder := TIdMessageDecoderMIME.Create(nil);
////                        try
////                          AMimeDecoder.SourceStream:=ARequestInfo.PostStream;
////                          AMimeDecoder.FreeSourceStream:=False;
////                          //一定要设置MIMEBoundary,不然ReadBody会结束不了,死循环
////                          TIdMessageDecoderMIME(AMimeDecoder).MIMEBoundary := Copy(AMimeDecoder.ReadLn(),3,MaxInt);
////                          AMimeDecoder.ReadHeader;
////                          repeat
////                            case AMimeDecoder.PartType of
////                              mcptText:
////                              begin
////                              end;
////                              mcptAttachment:
////                              begin
////                                //获取到name和文件
////                                if AMimeDecoder.Headers.Values['Content-Type']<>'' then
////                                begin
////
////                                    AIdHeaderList:=TIdHeaderList.Create(QuoteRFC822);
////                                    try
////                                      AIdHeaderList.AddStrings(AMimeDecoder.Headers);
////
////                                      //获取FileName
////                                      AFileName:=AIdHeaderList.Params['Content-Disposition','filename'];
////                                      AFileExt:=ExtractFileExt(AFileName);
////                                      AContentType:=AIdHeaderList.Values['Content-Type'];
////                                    finally
////                                      FreeAndNil(AIdHeaderList);
////                                    end;
////
////
////                                    ABodyStream:=TMemoryStream.Create;
////                                    try
////
////                                      //如果Encoding为空,那么Decoder.ReadBody默认为7bit格式读取
////                                      //但是plupload上传的是8bit格式的,所以要指定
////                                      if AMimeDecoder.Headers.Values['Content-Transfer-Encoding']='' then
////                                      begin
////                                        AMimeDecoder.Headers.Values['Content-Transfer-Encoding']:='8bit';
////                                      end;
////                                      AMimeDecoder.ReadBody(ABodyStream,msgEnd);
////
////
////                                      ARemoteFilePath:='';
////                                      if ProcessUploadFile(WWWRootDir,
////                                                           AAppID,
////                                                           AFileExt,
////                                                           AFileDir,
////                                                           ABodyStream,
////                                                           ARemoteFilePath,
////                                                           ACode,
////                                                           ADesc) then
////                                      begin
////                                        //上传成功
////                                      end;
////
////
////                                      //暂时只支持同时上传一个文件
////                                      Break;
////
////                                    finally
////                                      FreeAndNil(ABodyStream);
////                                    end;
////                                end;
////                              end;
////                              mcptIgnore: ;
////                              mcptEOF:
////                              begin
////                                Break;
////                              end;
////                            end;
////
////                            if AMimeDecoder.PartType<>mcptEOF then
////                            begin
////                              AMimeDecoder.Headers.Clear;
////                              AMimeDecoder.ReadHeader;
////                            end;
////
////                          until AMimeDecoder.PartType=mcptEOF;
////
////                        finally
////                          FreeAndNil(AMimeDecoder);
////                        end;
////
////                    end
////                    else
////                    begin
////                      ADesc:=('文件内容不能为空');
////                      Exit;
////                    end;
////                finally
////                  //返回
////                  ADataJson:=TSuperObject.Create;
////                  ADataJson.S['RemoteFilePath']:=ARemoteFilePath;
////                  ADataJson.S['Url']:=ReplaceStr(ARemoteFilePath,'\','/');
////                  AResponseInfo.ContentText:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
////                end;
////
////        end
////        else if SameText(LFilename,'/get_web_url') then
////        begin
////                AUrl:=EncdDecd.DecodeString(ARequestInfo.Params.Values['url']);
////                if AUrl<>'' then
////                begin
////                  ANetHttpClient:=TNetHttpClient.Create(nil);
////                  AResponseInfo.ContentStream:=TMemoryStream.Create;
////                  try
////                    try
////                      ANetHttpClient.Get(AUrl,AResponseInfo.ContentStream);
////                    except
////                      on E:Exception do
////                      begin
////                        uBaseLog.HandleException(E,'TdmFileIndyHttpServer.IdHTTPServerCommandGet ANetHttpClient.Get '+AUrl);
////                      end;
////                    end;
////                  finally
////                    FreeAndNil(ANetHttpClient);
////                  end;
////                end;
////        end
////        else
////        begin
////
////                //下载图片
////
////                //请求文件
////                if LFilename = '/' then
////                begin
////                  LFilename := 'index.html';
////                end;
////                LFilename:=ReplaceStr(LFilename,'/','\');
////
////                if LFilename[1]='\' then
////                begin
////                  LFilename:=Copy(LFilename,2,MaxInt);
////                end;
////
////                LPathname := WWWRootDir + LFilename;
////                if FileExists(LPathname) then
////                begin
////
////                  //D:\MyFiles\OrangeUIProduct\济胜汽修接车APP\Server\Win32\Debug\Upload\1003\Update\emp\Version.ini
////                  //D:\MyFiles\OrangeUIProduct\OpenPlatform\Server\Win32\Debug\Upload\1003\Update\emp
////      //              uBaseLog.HandleException(nil,'TdmFileIndyHttpServer.IdHTTPServerCommandGet 文件存在');
////                    try
////
////                        AResponseInfo.ContentStream := TFileStream.Create(LPathname, fmOpenRead + fmShareDenyWrite);//发文件
////
////                        if (LowerCase(ExtractFileExt(LFilename))='.jpg') then
////                        begin
////                          AResponseInfo.ContentType:='image/jpeg';
////                        end
////                        else if (LowerCase(ExtractFileExt(LFilename))='.png') then
////                        begin
////                          AResponseInfo.ContentType:='image/png';
////                        end
////                        else //if (LowerCase(ExtractFileExt(LFilename))='.csv') then //在网页上点击能下载，而不是直接在页面中显示内容
////                        begin
////                          AResponseInfo.ContentType:='application/octet-stream';
////                        end;
////                    except
////                      on E:Exception do
////                      begin
////                        uBaseLog.HandleException(E,'TdmFileIndyHttpServer.IdHTTPServerCommandGet');
////                      end;
////                    end;
////
////                end
////                else
////                begin
////      //              uBaseLog.HandleException(nil,'TdmFileIndyHttpServer.IdHTTPServerCommandGet 文件不存在');
////                    AResponseInfo.ResponseNo := 404;
////                    AResponseInfo.ContentText := '找不到' + ARequestInfo.Document;
////                end;
////
////        end;
//
//
//
//
//
////  finally
////    vl.Free ;
////  end;
//
////   SetResponseMimeType('text/html');
//
//
//end;

function TsrvFileManageRestService.EchoString(const AString: String): String;
begin
  Result:='你好！'+astring;
end;


function TsrvFileManageRestService.HelloWorld:String;
begin
  Result:='Hello world';
end;


function TsrvFileManageRestService.ProcessRequest(const Func: string;
  const ClientIdent: TkbmMWClientIdentity;
  const Args: array of Variant): Variant;
var
  ADesc:String;
  AStartTime:TDateTime;
begin
  AStartTime:=Now;

  ProcessCORSRequest;

  //如果没有方法名,则是下载文件，Variant能返回一个stream，返回自己释放吗？


  if (length(Args)>2)
    and (ClientIdent.ServicePath<>'/filemanage/format_excel_file')
    and (ClientIdent.ServicePath<>'/filemanage/upload_form')
  then
  begin

    //验签
    //取到appid,获取到appsecret,再验签,appid放在列表中,每次服务器启动时获取签名
    if not GlobalServiceProject.CheckInterfaceSign(ClientIdent,RequestTransportStream,Args[0],Args[2],ADesc) then
    begin
      Result:=ReturnJson(FAIL,ADesc,nil).AsJSON;
      Exit;
    end;

  end;


  Result:=Inherited;

  //统计接口调用
  GlobalServiceProject.FAPICallStatisticsList.AddCall(ClientIdent.ServicePath,DateUtils.MilliSecondsBetween(Now,AStartTime));

end;

function TsrvFileManageRestService.Upload(const AAppID: String;
  const key, AFileDir,AFileName:String;AFileExt:String; const ARemoteLocation: String): String;
var

  ARemoteFilePath:String;

  ACode:Integer;
  ADesc:String;
  ADataJson:ISuperObject;
  AUserAccessToken:TUserAccessToken;
begin

  //上传文件
  ACode:=FAIL;
  ADesc:='';
  ADataJson:=nil;


  AUserAccessToken:=GlobalServiceProject.FUserAccessTokenList.Find(key);

  if AUserAccessToken=nil then
  begin
    //匿名用户也能保存
    ADesc:='key:'+key+'无效或已过期';
    Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
    Exit;
  end;

  try

      if AFileExt='' then
      begin
        AFileExt:=ExtractFileExt(AFileName);
      end;

      ARemoteFilePath:='';
      if ProcessUploadFile(GetApplicationPath,//ExtractFilePath(Application.ExeName),
                           AAppID,
                           AFileName,
                           AFileExt,
                           AFileDir,
                           RequestStream,
                           ARemoteFilePath,
                           ACode,
                           ADesc) then
      begin
        //上传成功
      end;

  finally
      //返回
      ADataJson:=TSuperObject.Create;
      ADataJson.S['RemoteFilePath']:=ARemoteFilePath;
      ADataJson.S['Url']:=ReplaceStr(ARemoteFilePath,'\','/');
      Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
  end;

end;




function TsrvFileManageRestService.format_excel_file(//const key: String;
//AFileDir,AFileName: String;
const ARemoteLocation: String): String;
var
  AFileExt:String;
  ARemoteFilePath:String;

  ACode:Integer;
  ADesc:String;
  ADataJson:ISuperObject;
  AUserAccessToken:TUserAccessToken;

  AMimeDecoder:TIdMessageDecoderMIME;
  AMemoryStream:TMemoryStream;
  AName:String;
//  AStartIndex:Integer;
  msgEnd:Boolean;
  AFileName:String;
  ASheetFormatList:ISuperArray;
  AStringStream:TStringStream;
begin

  //上传文件
  ACode:=FAIL;
  ADesc:='';
  ADataJson:=nil;


//  AUserAccessToken:=GlobalServiceProject.FUserAccessTokenList.Find(key);
//
//  if AUserAccessToken=nil then
//  begin
//    //匿名用户也能保存
//    ADesc:='key:'+key+'无效或已过期';
//    Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
//    Exit;
//  end;

  try


      //------WebKitFormBoundaryq4GqiQCROcAGnVty
      //Content-Disposition: form-data; name="object"; filename="26_index_preview.png"
      //Content-Type: image/png



      AMemoryStream:=TMemoryStream.Create;
      AMimeDecoder := TIdMessageDecoderMIME.Create(nil);
      try
        AMimeDecoder.SourceStream:=RequestStream;
        AMimeDecoder.FreeSourceStream:=False;
        //一定要设置MIMEBoundary,不然ReadBody会结束不了,死循环
        TIdMessageDecoderMIME(AMimeDecoder).MIMEBoundary := Copy(AMimeDecoder.ReadLn(),3,MaxInt);
        AMimeDecoder.ReadHeader;
        repeat
          case AMimeDecoder.PartType of
            mcptText:
            begin
//              //取到参数json
//              AStringStream:=TStringStream.Create('',TEncoding.UTF8);
//              try
//                AMimeDecoder.ReadBody(AStringStream,msgEnd);
//
//                ASheetFormatList:=SA(AStringStream.DataString);
//              finally
//                FreeAndNil(AStringStream);
//              end;

            end;
            mcptAttachment:
            begin
              //'form-data; name="sheet_format_list"'

              //Content-Disposition: form-data; name="object"; filename="26_index_preview.png"


              //如果Encoding为空,那么Decoder.ReadBody默认为7bit格式读取
              //但是plupload上传的是8bit格式的,所以要指定
              if AMimeDecoder.Headers.Values['Content-Transfer-Encoding']='' then
              begin
                AMimeDecoder.Headers.Values['Content-Transfer-Encoding']:='8bit';
              end;

              AMemoryStream.Size:=0;
              AMimeDecoder.ReadBody(AMemoryStream,msgEnd);
              AMemoryStream.Position:=0;

//
//              //'form-data; name="page_json"; filename="page1.json"'
//              //取出name
//              AName:=AMimeDecoder.Headers.Values['Content-Disposition'];
//              AStartIndex:=Pos('name="',AName);
//              AName:=Copy(AName,AStartIndex+Length('name="'),MaxInt);
//              AStartIndex:=Pos('"',AName);
//              AName:=Copy(AName,1,AStartIndex-1);
//
//              //取出filename
//              AFileName:=AMimeDecoder.Headers.Values['Content-Disposition'];
//              AStartIndex:=Pos('filename="',AFileName);
//              AFileName:=Copy(AFileName,AStartIndex+Length('filename="'),MaxInt);
//              AStartIndex:=Pos('"',AFileName);
//              AFileName:=Copy(AFileName,1,AStartIndex-1);


              GetMimeDecoderParam(AMimeDecoder,AName,AFileName);
              if AName='sheet_format_list' then
              begin
                  AStringStream:=TStringStream.Create('',TEncoding.UTF8);
                  try
                    AStringStream.LoadFromStream(AMemoryStream);

                    ASheetFormatList:=SA(AStringStream.DataString);

                  finally
                    AStringStream.Free;
                  end;
              end
              else //if AName='excel_file' then
              begin
                  //获取到stream,然后用XlsReadWrtie解析即可

                  //
                  ADataJson:=TSuperObject.Create;

            //      //返回
            //      ADataJson.S['RemoteFilePath']:=ARemoteFilePath;
            //      ADataJson.S['Url']:=ReplaceStr(ARemoteFilePath,'\','/');

                  //返回一个二维数组就可以了，以方便nodejs进行解析
//                  ADataJson.A['SheetList']:=GetExcelFileContent(AMemoryStream,ASheetFormatList,System.NetEncoding.TNetEncoding.Url.Decode(AName));


                  ACode:=SUCC;
                  ADesc:='解析成功';
                  //不然会卡住
                  Break;
              end;



//              AMemoryStream.Position:=0;
//              ASaveDir:=GetApplicationPath+'webfiles'+PathDelim+'files'+PathDelim+'programs'+PathDelim;
//
//              SysUtils.ForceDirectories(ASaveDir);
//              AMemoryStream.SaveToFile(ASaveDir+AFileName);



//              Break;

            end;
            mcptIgnore: ;
            mcptEOF:
            begin
              Break;
            end;
          end;

          if AMimeDecoder.PartType<>mcptEOF then
          begin
            AMimeDecoder.Headers.Clear;
            AMimeDecoder.ReadHeader;
          end;

        until AMimeDecoder.PartType=mcptEOF;



      finally
        FreeAndNil(AMimeDecoder);
        FreeAndNil(AMemoryStream);
      end;



//      if AFileExt='' then
//      begin
//        AFileExt:=ExtractFileExt(AFileName);
//      end;
//      AFileDir:=ReplaceStr(AFileDir,'/',PathDelim);
//      AFileDir:=ReplaceStr(AFileDir,'\',PathDelim);
//
//      ARemoteFilePath:='';
//      if not ProcessUploadFile(GetApplicationPath,//ExtractFilePath(Application.ExeName),
//                           '',
//                           AFileName,
//                           AFileExt,
//                           AFileDir,
//                           RequestStream,
//                           ARemoteFilePath,
//                           ACode,
//                           ADesc) then
//      begin
//        //上传失败和
//        Exit;
//      end;


  finally
      Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
  end;


end;

function TsrvFileManageRestService.upload_file(const key:String; AFileDir:String;const AFileName, ARemoteLocation: String): String;
var
  AFileExt:String;
  ARemoteFilePath:String;

  ACode:Integer;
  ADesc:String;
  ADataJson:ISuperObject;
  AUserAccessToken:TUserAccessToken;
begin

  //上传文件
  ACode:=FAIL;
  ADesc:='';
  ADataJson:=nil;


  AUserAccessToken:=GlobalServiceProject.FUserAccessTokenList.Find(key);

  if AUserAccessToken=nil then
  begin
    //匿名用户也能保存
    ADesc:='key:'+key+'无效或已过期';
    Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
    Exit;
  end;

  try

      if AFileExt='' then
      begin
        AFileExt:=ExtractFileExt(AFileName);
      end;
      AFileDir:=ReplaceStr(AFileDir,'/',PathDelim);
      AFileDir:=ReplaceStr(AFileDir,'\',PathDelim);

      ARemoteFilePath:='';
      if ProcessUploadFile(GetApplicationPath,//ExtractFilePath(Application.ExeName),
                           '',
                           AFileName,
                           AFileExt,
                           AFileDir,
                           RequestStream,
                           ARemoteFilePath,
                           ACode,
                           ADesc) then
      begin
        //上传成功
      end;

  finally
      //返回
      ADataJson:=TSuperObject.Create;
      ADataJson.S['RemoteFilePath']:=ARemoteFilePath;
      ADataJson.S['Url']:=ReplaceStr(ARemoteFilePath,'\','/');
      Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
  end;


end;

function TsrvFileManageRestService.Upload_form(const //AAppID,
ARemoteLocation: String): String;
var
  AFileExt:String;
  ARemoteFilePath:String;

  ACode:Integer;
  ADesc:String;
  ADataJson:ISuperObject;
  AUserAccessToken:TUserAccessToken;

  AMimeDecoder:TIdMessageDecoderMIME;
  AMemoryStream:TMemoryStream;
  AName:String;
//  AStartIndex:Integer;
  msgEnd:Boolean;
  AMimeFileName:String;
  ASheetFormatList:ISuperArray;
  AStringStream:TStringStream;

  AMetaData:String;
  ABucketName:String;
  AData:String;
  AIntfItem:TCommonRestIntfItem;

  ASuperObject:ISuperObject;
  AFileSize:Integer;
  AFileName:String;
begin

  //上传文件
  ACode:=FAIL;
  ADesc:='';
  ADataJson:=nil;


//  AUserAccessToken:=GlobalServiceProject.FUserAccessTokenList.Find(key);
//
//  if AUserAccessToken=nil then
//  begin
//    //匿名用户也能保存
//    ADesc:='key:'+key+'无效或已过期';
//    Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
//    Exit;
//  end;

  try




      //------WebKitFormBoundaryq4GqiQCROcAGnVty
      //Content-Disposition: form-data; name="object"; filename="26_index_preview.png"
      //Content-Type: image/png


      AFileSize:=0;
      AMemoryStream:=TMemoryStream.Create;
      AMimeDecoder := TIdMessageDecoderMIME.Create(nil);
      try
        AMimeDecoder.SourceStream:=RequestStream;
        AMimeDecoder.FreeSourceStream:=False;
        //一定要设置MIMEBoundary,不然ReadBody会结束不了,死循环
        TIdMessageDecoderMIME(AMimeDecoder).MIMEBoundary := Copy(AMimeDecoder.ReadLn(),3,MaxInt);
        AMimeDecoder.ReadHeader;
        repeat
//          case AMimeDecoder.PartType of
//            mcptText:
//            begin
              //取到参数json
              AStringStream:=TStringStream.Create('',TEncoding.UTF8);
              try
                AMimeDecoder.ReadBody(AStringStream,msgEnd);

                GetMimeDecoderParam(AMimeDecoder,AName,AMimeFileName);
                if AName='metadata' then
                begin
                  AMetaData:=Trim(AStringStream.DataString);
                end;
                if AName='bucketName' then
                begin
                  ABucketName:=Trim(AStringStream.DataString);
                end;
                if AName='data' then
                begin
                  AData:=Trim(AStringStream.DataString);
                end;
                if AName='file' then
                begin

                  AFileName:=AMimeFileName;
                  AFileExt:=ExtractFileExt(AMimeFileName);

                  AFileSize:=AStringStream.Size;

                  //保存成文件
                  ARemoteFilePath:='';
                  if ProcessUploadFile(GetApplicationPath,//ExtractFilePath(Application.ExeName),
                                       '',
                                       AFileName,
                                       AFileExt,
                                       ABucketName+PathDelim,
                                       AStringStream,
                                       ARemoteFilePath,
                                       ACode,
                                       ADesc) then
                  begin
                    //上传成功
                  end;

                end;



//                ASheetFormatList:=SA(AStringStream.DataString);
              finally
                FreeAndNil(AStringStream);
              end;

//            end;
//            mcptAttachment:
//            begin
//              //'form-data; name="sheet_format_list"'
//
//              //Content-Disposition: form-data; name="object"; filename="26_index_preview.png"
//
//
//              //如果Encoding为空,那么Decoder.ReadBody默认为7bit格式读取
//              //但是plupload上传的是8bit格式的,所以要指定
//              if AMimeDecoder.Headers.Values['Content-Transfer-Encoding']='' then
//              begin
//                AMimeDecoder.Headers.Values['Content-Transfer-Encoding']:='8bit';
//              end;
//
//              AMemoryStream.Size:=0;
//              AMimeDecoder.ReadBody(AMemoryStream,msgEnd);
//              AMemoryStream.Position:=0;
//
////
////              //'form-data; name="page_json"; filename="page1.json"'
////              //取出name
////              AName:=AMimeDecoder.Headers.Values['Content-Disposition'];
////              AStartIndex:=Pos('name="',AName);
////              AName:=Copy(AName,AStartIndex+Length('name="'),MaxInt);
////              AStartIndex:=Pos('"',AName);
////              AName:=Copy(AName,1,AStartIndex-1);
////
////              //取出filename
////              AFileName:=AMimeDecoder.Headers.Values['Content-Disposition'];
////              AStartIndex:=Pos('filename="',AFileName);
////              AFileName:=Copy(AFileName,AStartIndex+Length('filename="'),MaxInt);
////              AStartIndex:=Pos('"',AFileName);
////              AFileName:=Copy(AFileName,1,AStartIndex-1);
//
//
//              GetMimeDecoderParam(AMimeDecoder,AName,AFileName);
//              AFileExt:=ExtractFileExt(AFileName);
//
//              //保存成文件
//              ARemoteFilePath:='';
//              if ProcessUploadFile(GetApplicationPath,//ExtractFilePath(Application.ExeName),
//                                   '',
//                                   AFileName,
//                                   AFileExt,
//                                   ABucketName,
//                                   AMemoryStream,
//                                   ARemoteFilePath,
//                                   ACode,
//                                   ADesc) then
//              begin
//                //上传成功
//              end;
//
//
////              if AName='file' then
////              begin
////                  AStringStream:=TStringStream.Create('',TEncoding.UTF8);
////                  try
////                    AStringStream.LoadFromStream(AMemoryStream);
////
////                    ASheetFormatList:=SA(AStringStream.DataString);
////
////                  finally
////                    AStringStream.Free;
////                  end;
////              end
////              else //if AName='excel_file' then
////              begin
////                  //获取到stream,然后用XlsReadWrtie解析即可
////
////                  //
////                  ADataJson:=TSuperObject.Create;
////
////            //      //返回
////            //      ADataJson.S['RemoteFilePath']:=ARemoteFilePath;
////            //      ADataJson.S['Url']:=ReplaceStr(ARemoteFilePath,'\','/');
////
////                  //返回一个二维数组就可以了，以方便nodejs进行解析
//////                  ADataJson.A['SheetList']:=GetExcelFileContent(AMemoryStream,ASheetFormatList,System.NetEncoding.TNetEncoding.Url.Decode(AName));
////
////
////                  ACode:=SUCC;
////                  ADesc:='解析成功';
////                  //不然会卡住
////                  Break;
////              end;
//
//
//
////              AMemoryStream.Position:=0;
////              ASaveDir:=GetApplicationPath+'webfiles'+PathDelim+'files'+PathDelim+'programs'+PathDelim;
////
////              SysUtils.ForceDirectories(ASaveDir);
////              AMemoryStream.SaveToFile(ASaveDir+AFileName);
//
//
//
////              Break;
//
//            end;
//            mcptIgnore: ;
//            mcptEOF:
//            begin
//              Break;
//            end;
//          end;



          if AMimeDecoder.PartType<>mcptEOF then
          begin
            AMimeDecoder.Headers.Clear;
            AMimeDecoder.ReadHeader;
          end;

          // 没有头了,说明没有数据了
          if AMimeDecoder.Headers.Count=0 then
          begin
            break;
          end;



        until AMimeDecoder.PartType=mcptEOF;



        ASuperObject:=SO();
        ASuperObject.S['_id']:=CreateGUIDString;
        ASuperObject.S['teamId']:='';
        ASuperObject.S['tmbId']:='';
        ASuperObject.I['length']:=AFileSize;
        ASuperObject.I['chunkSize']:=261120;
        ASuperObject.S['filename']:=AFileName;
        ASuperObject.S['filepath']:=ARemoteFilePath;


        AIntfItem:=CommonRestServiceModule.IntfList.Find(ABucketName+'_files');
        if AIntfItem=nil then
        begin
          ADesc:='不存在'+ABucketName+'_files'+'接口';
          Exit;
        end;

        //新增
        AIntfItem.AddRecord(AIntfItem.DBModule,
                            nil,
                            '',
                            ASuperObject,
                            nil,
                            ACode,
                            ADesc,
                            ADataJson
                            );

        if ADataJson=nil then
        begin
          ADataJson:=SO();
          ADataJson.S['fileId']:=ASuperObject.S['_id'];
        end;


      finally
        FreeAndNil(AMimeDecoder);
        FreeAndNil(AMemoryStream);
      end;

//      if AFileExt='' then
//      begin
//        AFileExt:=ExtractFileExt(AFileName);
//      end;
//      AFileDir:=ReplaceStr(AFileDir,'/',PathDelim);
//      AFileDir:=ReplaceStr(AFileDir,'\',PathDelim);
//
//      ARemoteFilePath:='';
//      if not ProcessUploadFile(GetApplicationPath,//ExtractFilePath(Application.ExeName),
//                           '',
//                           AFileName,
//                           AFileExt,
//                           AFileDir,
//                           RequestStream,
//                           ARemoteFilePath,
//                           ACode,
//                           ADesc) then
//      begin
//        //上传失败和
//        Exit;
//      end;


  finally
      Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
  end;



end;

{ TFileManageServiceModule }

procedure TFileManageServiceModule.AddWWWRootDir(AWWWRootDir: String);
var
  I:Integer;
  AServiceList:TList<TkbmMWCustomServiceDefinition>;
begin
  AServiceList:=GlobalServiceProject.kbmMWServer1.DefinedServiceList.Services.BeginWrite;
  try
    for I := 0 to AServiceList.Count-1 do
    begin
      if TkbmMWHTTPServiceDefinition(AServiceList[I]).ServiceClass.ClassName='TsrvFileManageRestService' then
      begin
          //如果图片不存在,则在AWWWRootDir这个目录中找

          //mwhuroCheckFileExists,存在这个文件就用这个路径,如果不存在,则不替换链接
          //http://127.0.0.1:10050/filemanage/20141208-00013.jpg
          //订单图片
          {$IFDEF MSWINDOWS}
          TkbmMWHTTPServiceDefinition(AServiceList[I]).Rewrites.Add('/filemanage/',AWWWRootDir,[mwhuroCheckFileExists]);
          {$ENDIF}

      end;
    end;
  finally
    GlobalServiceProject.kbmMWServer1.DefinedServiceList.Services.EndWrite;
  end;

end;

constructor TFileManageServiceModule.Create;
begin
  inherited;

//  kbmMWFilePool1:=TkbmMWFilePool.Create(nil);

  dmFileIndyHttpServer:=TdmFileIndyHttpServer.Create(nil);
//  WWWRootDirList:=TStringList.Create;
end;

destructor TFileManageServiceModule.Destroy;
begin
//  FreeAndNil(WWWRootDirList);
//  FreeAndNil(kbmMWFilePool1);

  FreeAndNil(dmFileIndyHttpServer);
  inherited;
end;



procedure TFileManageServiceModule.DoAfterStart;
var
  I:Integer;
  AServiceList:TList<TkbmMWCustomServiceDefinition>;
begin
  Inherited;

  AServiceList:=GlobalServiceProject.kbmMWServer1.DefinedServiceList.Services.BeginWrite;
  try
    for I := 0 to AServiceList.Count-1 do
    begin
      if TkbmMWHTTPServiceDefinition(AServiceList[I]).ServiceClass.ClassName='TsrvFileManageRestService' then
      begin
          TkbmMWHTTPServiceDefinition(AServiceList[I]).RootPath[mwhfcHTML]:='';
          TkbmMWHTTPServiceDefinition(AServiceList[I]).RootPath[mwhfcImage]:='';
          TkbmMWHTTPServiceDefinition(AServiceList[I]).RootPath[mwhfcJavascript]:='';
          TkbmMWHTTPServiceDefinition(AServiceList[I]).RootPath[mwhfcStyleSheet]:='';
          TkbmMWHTTPServiceDefinition(AServiceList[I]).RootPath[mwhfcOther]:='';

          //mwhuroBreak,替换完就结束
          //mwhuroIfFileNotExists,如果文件不存在,则使用
          //mwhuroCheckFileExists,使用之前判断文件是否存在

          //将链接中的filemanage替换成根目录
          //http://127.0.0.1:10050/filemanage/Upload/1016/quality_check_pic/2022/2022-04-01/871726F7276C4A7481A547688D65344A.png
          TkbmMWHTTPServiceDefinition(AServiceList[I]).Rewrites.Add('/filemanage/','',[]);


      end;
    end;
  finally
    GlobalServiceProject.kbmMWServer1.DefinedServiceList.Services.EndWrite;
  end;


end;

function TFileManageServiceModule.DoPrepareStart(var AError:String): Boolean;
//var
//   sd:TkbmMWHTTPServiceDefinition;
begin
  Result:=False;

  Inherited;

//  sd:=TkbmMWHTTPServiceDefinition(GlobalServiceProject.kbmMWServer1.RegisterService(TkbmMWEventFileHTTPService,false));
//  sd.RootPath[mwhfcHTML]:=ExtractFilePath(Application.ExeName);//'webfiles/';
//  sd.RootPath[mwhfcHTML]:='webfiles/';
//  sd.RootPath[mwhfcImage]:=ExtractFilePath(Application.ExeName);//'webfiles/images';
//  sd.RootPath[mwhfcJavascript]:='webfiles/js';
//  sd.RootPath[mwhfcStyleSheet]:='webfiles/css';
//  sd.RootPath[mwhfcOther]:=ExtractFilePath(Application.ExeName);//'webfiles/files';

//             sd:=TkbmMWHTTPServiceDefinition(kbmMWServer1.RegisterService(TkbmMWEventHTTPService2,false));
//             TkbmMWHTTPServiceDefinition(sd).RootPath[mwhfcHTML]:='webfiles/';
//             TkbmMWHTTPServiceDefinition(sd).RootPath[mwhfcImage]:='upload/';
//             TkbmMWHTTPServiceDefinition(sd).RootPath[mwhfcJavascript]:='';
//             TkbmMWHTTPServiceDefinition(sd).RootPath[mwhfcStyleSheet]:='';
//             TkbmMWHTTPServiceDefinition(sd).RootPath[mwhfcOther]:='';



  //启动Http上传下载服务
  //443+1
  if GlobalServiceProject.SSLPort<>0 then
  begin
      if GlobalServiceProject.Port=10000 then
      begin
        Self.dmFileIndyHttpServer.SetPort(GlobalServiceProject.Port+1,446);
      end
      else
      begin
        Self.dmFileIndyHttpServer.SetPort(GlobalServiceProject.Port+1,GlobalServiceProject.Port+445);
      end;
      Self.dmFileIndyHttpServer.SetSSL(True);
  end
  else
  begin
      Self.dmFileIndyHttpServer.SetPort(GlobalServiceProject.Port+1,0);
      Self.dmFileIndyHttpServer.SetSSL(False);
  end;
  Self.dmFileIndyHttpServer.IdHTTPServer.Active:=True;





  Result:=True;
end;

function TFileManageServiceModule.DoPrepareStop: Boolean;
begin
  Result:=False;


  //停止Http上传下载服务
  Self.dmFileIndyHttpServer.IdHTTPServer.Active:=False;

  Inherited;

  Result:=True;
end;

procedure TFileManageServiceModule.Init;
var
  AIntfItem:TCommonRestIntfItem;
  ADataFlowAction:TDataFlowAction;
begin


  {$REGION '文件上传表'}
  //用户表的临时变量的增删改查接口
  AIntfItem:=TCommonRestIntfItem.Create(
    //名称
    'dataset_files',
    //名称
    '知识库文件上传表',
    //数据库连接
    FileManageRestService.FileManageServiceModule.DBModule,
    //表名
    'dataset_files',
    '',
//    'SELECT * FROM ( '
//      +' SELECT '
//      +' A.*, '
//      +' B.name as introducer_name,B.phone as introducer_phone '
//      +' FROM tbluser A '
//      +' LEFT JOIN tbluser B ON A.appid=B.appid and B.fid=A.bind_introducer_fid '
//      +' ) view_user ',
    '',
    //删除字段
    '',
    //主键字段
    '_id',
    //默认排序
    '',
    True);
  CommonRestServiceModule.IntfList.Add(AIntfItem);
  {$ENDREGION '用户表'}



end;

initialization
  TkbmMWRTTI.EnableRTTI(TsrvFileManageRestService);

  //服务模块
  FileManageServiceModule:=TFileManageServiceModule.Create();
  FileManageServiceModule.DBModule.DBConfigFileName:='FileManagerDBConfig.ini';
  FileManageServiceModule.DBModule.DBConfig.FDBDataBaseName:='rag_center';
  FileManageServiceModule.Name:='文件管理';
  FileManageServiceModule.kbmMWCustomServiceClass:=TsrvFileManageRestService;
  //注册
  RegisterServiceModule(FileManageServiceModule);



finalization
  FreeAndNil(FileManageServiceModule);



end.
