//convert pas to utf8 by ¥

unit RagCenterRestService;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding services unit name
// to it. Eg.
//
//     uses ...,kbmMWServer,YourServiceUnitName;
//
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance.
// This can be done by registering the traditional way, or by using auto registration.
//
// Traditional registration
// ------------------------
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
//
// Set the last parameter to true if this is the default service.
//
//
// Auto registration
// -----------------
// Make sure that your service class is tagged with the [kbmMW_Service] attribute.
// Then auto register all tagged services:
// ..
//    kbmMWServer1.AutoRegisterServices;
//
// -----------------------------------------------


{$I OpenPlatformServer.inc}

{$I kbmMW.inc}

interface

uses
  SysUtils,
{$ifdef LEVEL6}
  Variants,
{$else}
  Forms,
{$endif}
  Classes,
  DateUtils,
  Math,


//  MD5,
  StrUtils,
  IniFiles,
  XSuperObject,
  XSuperJson,
  uBaseList,
//  uFuncCommon,

//  uThumbCommon,
//  uDateCommon,
//  uCaptcha,
//  uCommonUtils,
  uDataSetToJson,
  uBaseDBHelper,
  uBaseHttpControl,
  uFileCommon,
  IdURI,
//  uDatesetToJson,
  uUniDBHelper,
  uFuncCommon,
//  uLang,
  EncdDecd,
  {$IFDEF HAS_CONTENT_SEARCH}
  uJobData,
  TaskManagerRestService,
  {$ENDIF}

  uBaseLog,
  uTimerTask,
  DB,

  uRestInterfaceCall,
  {$IFDEF HAS_LICENSE_CHECK}
  uOEM,
  uLicenseCheck,
  {$ENDIF}


  uOpenCommon,
  RagServer,
//  uDBTableCopy,

  uOpenPlatformServerManager,
//  uEasyServiceCommon,

  uTableCommonRestCenter,
  TableCommonRestService,

  //有些APP要启用IM,添加了用户之后要添加FastMsg的账号
//  uFastMsgWebService_default,
  System.Hash,

  IdMessageCoder,
  IdMessageCoderMIME,
  System.NetEncoding,
  FileIndyHttpServerModule,


  kbmMWSecurity,
  kbmMWServer,
  kbmMWServiceUtils,

  kbmMWHTTPStdTransStream,
  kbmMWCustomHTTPSmartService,

  kbmMWGlobal,
  kbmMWCustomSmartService
   ,kbmMWRTTI
   ,kbmMWSmartServiceUtils;


type
  [kbmMW_Service('name:ragcenter, flags:[listed]')]
  [kbmMW_Rest('path:/ragcenter')]
  // Access to the service can be limited using the [kbmMW_Auth..] attribute.
  // [kbmMW_Auth('role:[SomeRole,SomeOtherRole], grant:true')]

  TsrvRagCenterRestService = class(TkbmMWCustomHTTPSmartService)
    procedure kbmMWCustomHTTPSmartServiceCORS(Sender: TObject;
      const ARequestHelper, AResponseHelper: TkbmMWHTTPTransportStreamHelper;
      const AOrigin: string; var AAllowedOrigins, AAllowedMethods,
      AAllowedHeaders: string);

     { Private declarations }
  protected
     { Protected declarations }
  public
     { Public declarations }
     // HelloWorld function callable from both a regular client,
     // due to the optional [kbmMW_Method] attribute,
     // and from a REST client due to the optional [kbmMW_Rest] attribute.
     // The access path to the function from a REST client (like a browser)+
     // is in this case relative to the services path.
     // In this example: http://.../xalionservice/helloworld
     // Access to the function can be limited using the [kbmMW_Auth..] attribute.
     // [kbmMW_Auth('role:[SomeRole,SomeOtherRole], grant:true')]

     //http://127.0.0.1:9000/easyservice/helloworld
     //http://127.0.0.1:9000/easyservice/echostring/abc
     //http://127.0.0.1:9000/easyservice/cal/addnumbers?arg1=1&arg2=2
     //http://127.0.0.1:9000/easyservice/send_register_captcha?phone=18957901025
     //http://127.0.0.1:9000/easyservice/register_user?appid=1001&phone=18957901025&captcha=2721&name=ggggcexx&password=123456&repassword=123456


     //加了[kbmMW_Method]属性的方法才会被访问到
     //[kbmMW_Rest].method表示访问所使用的方法
     //[kbmMW_Rest].path表示访问的路径,可以有别名
     [kbmMW_Rest('method:get, path:helloworld')]
     [kbmMW_Method]
     function HelloWorld:String;


     //回应输入的串
     [kbmMW_Method('EchoString')]
     [kbmMW_Rest('method:get, path: [ "echostring/{AString}","myechostring/{AString}" ]')]
     [kbmMW_Auth('role:[SomeRole,SomeOtherRole], grant:true')]
     function EchoString([kbmMW_Rest('value: "{AString}"')] const AString:String):String;


     [kbmMW_Method]
     [kbmMW_Rest('method:get, path: "cal/addnumbers"')]
     function AddNumbers([kbmMW_Rest('value: "$arg1", required: false')] const AValue1:Integer;
                         [kbmMW_Rest('value: "$arg2", required: false')] const AValue2:Integer;
                         [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):Integer;

  public
    // 知识库管理接口

    // 知识库创建接口
    [kbmMW_Method]
    [kbmMW_Rest('method:post, path: "dataset/create"')]
    function dataset_create(
                    [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):String;

    // 知识库列表接口
    [kbmMW_Method]
    [kbmMW_Rest('method:post, path: "dataset/list"')]
    function dataset_list(
                    [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):String;

    //上传本地文件
    [kbmMW_Method]
    [kbmMW_Rest('method:post, path: "dataset/collection/create/localFile"')]
    function dataset_collection_create_localFile(
                    [kbmMW_Arg(mwatRemoteLocation)] const ARemoteLocation:String):String;




  public
    function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;

  end;






  TRagCenterServiceModule=class(TKbmMWServiceModule)
  private
    //从别的APP复制配置到新APP
    function CustomCopyConfigFromApp(ASQLDBHelper:TBaseDBHelper;ASourceAppID:Integer;ADestAppID:Integer;ADestAppJson:ISuperObject;var ADesc:String):Boolean;override;
  public

    constructor Create; override;
    destructor Destroy; override;

//    procedure Init;override;
    //准备启动
    function DoPrepareStart(var AError:String): Boolean; override;
    //准备停止
    function DoPrepareStop: Boolean; override;
    //启动后
    procedure DoAfterStart;override;

  end;





var
  RagCenterServiceModule:TRagCenterServiceModule;


implementation




{$R *.dfm}


// Service definitions.
//---------------------


procedure TsrvRagCenterRestService.kbmMWCustomHTTPSmartServiceCORS(
  Sender: TObject; const ARequestHelper,
  AResponseHelper: TkbmMWHTTPTransportStreamHelper; const AOrigin: string;
  var AAllowedOrigins, AAllowedMethods, AAllowedHeaders: string);
begin
  AAllowedMethods:='GET,POST,OPTIONS' ;
  AAllowedOrigins:='*';//'http://127.0.0.1';
//  AAllowedHeaders:= 'x-requested-with';
  AAllowedHeaders:= '*';
end;


function TsrvRagCenterRestService.AddNumbers(const AValue1, AValue2: Integer;
  const ARemoteLocation: String): Integer;
begin
  Result:=AValue1+AValue2;
end;

function TsrvRagCenterRestService.ProcessRequest(const Func: string;
  const ClientIdent: TkbmMWClientIdentity;
  const Args: array of Variant): Variant;
var
  ADesc:String;
  AStartTime:TDateTime;
begin
  AStartTime:=Now;


  ProcessCORSRequest;

//  if (length(Args)>2)
//    and (ClientIdent.ServicePath<>'/ragcenter/helloworld')
//    and (ClientIdent.ServicePath<>'/ragcenter/echostring')
//
//
//    then
//  begin
////    uBaseLog.HandleException(nil,'TsrvRagCenterRestService.ProcessRequest Args[0]:'+Args[0]);
////    uBaseLog.HandleException(nil,'TsrvRagCenterRestService.ProcessRequest Args[1]:'+Args[1]);
////    uBaseLog.HandleException(nil,'TsrvRagCenterRestService.ProcessRequest Args[2]:'+Args[2]);
////    uBaseLog.HandleException(nil,'TsrvRagCenterRestService.ProcessRequest ClientIdent.ServicePath:'+ClientIdent.ServicePath);
//
//    //验签
//    //取到appid,获取到appsecret,再验签,appid放在列表中,每次服务器启动时获取签名
//    if not GlobalServiceProject.CheckInterfaceSign(ClientIdent,RequestTransportStream,ClientIdent.ServicePath,Args[2],ADesc) then
//    begin
//      Result:=ReturnJson(FAIL,ADesc,nil).AsJSON;
//      Exit;
//    end;
//
//  end;


  Result:=Inherited;


  //统计接口调用
  GlobalServiceProject.FAPICallStatisticsList.AddCall(ClientIdent.ServicePath,DateUtils.MilliSecondsBetween(Now,AStartTime));


end;


function TsrvRagCenterRestService.HelloWorld:String;
begin
  Result:='Hello world';
end;


function TsrvRagCenterRestService.dataset_collection_create_localFile(const ARemoteLocation: String): String;
var
  AFileExt:String;
  ARemoteFilePath:String;

  ACode:Integer;
  ADesc:String;
  ADataJson:ISuperObject;
  AUserAccessToken:TUserAccessToken;

  AMimeDecoder:TIdMessageDecoderMIME;
  AMemoryStream:TMemoryStream;
  AName:String;
//  AStartIndex:Integer;
  msgEnd:Boolean;
  AFileName:String;
  ASheetFormatList:ISuperArray;
  AStringStream:TStringStream;
begin

  //上传文件
  ACode:=FAIL;
  ADesc:='';
  ADataJson:=nil;


//  AUserAccessToken:=GlobalServiceProject.FUserAccessTokenList.Find(key);
//
//  if AUserAccessToken=nil then
//  begin
//    //匿名用户也能保存
//    ADesc:='key:'+key+'无效或已过期';
//    Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
//    Exit;
//  end;

  try


      //------WebKitFormBoundaryq4GqiQCROcAGnVty
      //Content-Disposition: form-data; name="object"; filename="26_index_preview.png"
      //Content-Type: image/png



      AMemoryStream:=TMemoryStream.Create;
      AMimeDecoder := TIdMessageDecoderMIME.Create(nil);
      try
        AMimeDecoder.SourceStream:=RequestStream;
        AMimeDecoder.FreeSourceStream:=False;
        //一定要设置MIMEBoundary,不然ReadBody会结束不了,死循环
        TIdMessageDecoderMIME(AMimeDecoder).MIMEBoundary := Copy(AMimeDecoder.ReadLn(),3,MaxInt);
        AMimeDecoder.ReadHeader;
        repeat
          case AMimeDecoder.PartType of
            mcptText:
            begin
//              //取到参数json
//              AStringStream:=TStringStream.Create('',TEncoding.UTF8);
//              try
//                AMimeDecoder.ReadBody(AStringStream,msgEnd);
//
//                ASheetFormatList:=SA(AStringStream.DataString);
//              finally
//                FreeAndNil(AStringStream);
//              end;

            end;
            mcptAttachment:
            begin
              //'form-data; name="sheet_format_list"'

              //Content-Disposition: form-data; name="object"; filename="26_index_preview.png"


              //如果Encoding为空,那么Decoder.ReadBody默认为7bit格式读取
              //但是plupload上传的是8bit格式的,所以要指定
              if AMimeDecoder.Headers.Values['Content-Transfer-Encoding']='' then
              begin
                AMimeDecoder.Headers.Values['Content-Transfer-Encoding']:='8bit';
              end;

              AMemoryStream.Size:=0;
              AMimeDecoder.ReadBody(AMemoryStream,msgEnd);
              AMemoryStream.Position:=0;

//
//              //'form-data; name="page_json"; filename="page1.json"'
//              //取出name
//              AName:=AMimeDecoder.Headers.Values['Content-Disposition'];
//              AStartIndex:=Pos('name="',AName);
//              AName:=Copy(AName,AStartIndex+Length('name="'),MaxInt);
//              AStartIndex:=Pos('"',AName);
//              AName:=Copy(AName,1,AStartIndex-1);
//
//              //取出filename
//              AFileName:=AMimeDecoder.Headers.Values['Content-Disposition'];
//              AStartIndex:=Pos('filename="',AFileName);
//              AFileName:=Copy(AFileName,AStartIndex+Length('filename="'),MaxInt);
//              AStartIndex:=Pos('"',AFileName);
//              AFileName:=Copy(AFileName,1,AStartIndex-1);


              GetMimeDecoderParam(AMimeDecoder,AName,AFileName);
              if AName='sheet_format_list' then
              begin
                  AStringStream:=TStringStream.Create('',TEncoding.UTF8);
                  try
                    AStringStream.LoadFromStream(AMemoryStream);

                    ASheetFormatList:=SA(AStringStream.DataString);

                  finally
                    AStringStream.Free;
                  end;
              end
              else //if AName='excel_file' then
              begin
                  //获取到stream,然后用XlsReadWrtie解析即可

                  //
                  ADataJson:=TSuperObject.Create;

            //      //返回
            //      ADataJson.S['RemoteFilePath']:=ARemoteFilePath;
            //      ADataJson.S['Url']:=ReplaceStr(ARemoteFilePath,'\','/');

                  //返回一个二维数组就可以了，以方便nodejs进行解析
//                  ADataJson.A['SheetList']:=GetExcelFileContent(AMemoryStream,ASheetFormatList,System.NetEncoding.TNetEncoding.Url.Decode(AName));


                  ACode:=SUCC;
                  ADesc:='解析成功';
                  //不然会卡住
                  Break;
              end;



//              AMemoryStream.Position:=0;
//              ASaveDir:=GetApplicationPath+'webfiles'+PathDelim+'files'+PathDelim+'programs'+PathDelim;
//
//              SysUtils.ForceDirectories(ASaveDir);
//              AMemoryStream.SaveToFile(ASaveDir+AFileName);



//              Break;

            end;
            mcptIgnore: ;
            mcptEOF:
            begin
              Break;
            end;
          end;

          if AMimeDecoder.PartType<>mcptEOF then
          begin
            AMimeDecoder.Headers.Clear;
            AMimeDecoder.ReadHeader;
          end;

        until AMimeDecoder.PartType=mcptEOF;



      finally
        FreeAndNil(AMimeDecoder);
        FreeAndNil(AMemoryStream);
      end;



//      if AFileExt='' then
//      begin
//        AFileExt:=ExtractFileExt(AFileName);
//      end;
//      AFileDir:=ReplaceStr(AFileDir,'/',PathDelim);
//      AFileDir:=ReplaceStr(AFileDir,'\',PathDelim);
//
//      ARemoteFilePath:='';
//      if not ProcessUploadFile(GetApplicationPath,//ExtractFilePath(Application.ExeName),
//                           '',
//                           AFileName,
//                           AFileExt,
//                           AFileDir,
//                           RequestStream,
//                           ARemoteFilePath,
//                           ACode,
//                           ADesc) then
//      begin
//        //上传失败和
//        Exit;
//      end;


  finally
      Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
  end;


end;

function TsrvRagCenterRestService.dataset_create(const ARemoteLocation: String): String;
var
  ACode:Integer;
  ADesc:String;
  ADataJson:ISuperObject;
  AStringStream:TStringStream;
  ASuperObject:ISuperObject;

  AIntfItem:TCommonRestIntfItem;
begin


  ACode:=FAIL;
  ADesc:='';
  ADataJson:=nil;

  AStringStream:=TStringStream.Create('',TEncoding.UTF8);
  try
    AStringStream.LoadFromStream(RequestStream);
    try
      ASuperObject:=SO(AStringStream.DataString);

      AIntfItem:=CommonRestServiceModule.IntfList.Find('datasets');
      if AIntfItem=nil then
      begin
        ADesc:='不存在datasets接口';
        Exit;
      end;

      //新增
      AIntfItem.AddRecord(AIntfItem.DBModule,
                          nil,
                          '',
                          ASuperObject,
                          nil,
                          ACode,
                          ADesc,
                          ADataJson
                          );

      Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;

    except
      on E:Exception do
      begin
        ADesc:=('RequestStream不是合法的Json格式');
        Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
        Exit;
      end;
    end;
  finally
    FreeAndNil(AStringStream);
  end;
end;

function TsrvRagCenterRestService.dataset_list(const ARemoteLocation: String): String;
var
  ACode:Integer;
  ADesc:String;
  ADataJson:ISuperObject;
  AStringStream:TStringStream;
  ASuperObject:ISuperObject;

  AIntfItem:TCommonRestIntfItem;
  AWhereKeyJsonArray:ISuperArray;
begin


  ACode:=FAIL;
  ADesc:='';
  ADataJson:=nil;

  AStringStream:=TStringStream.Create('',TEncoding.UTF8);
  try
    AStringStream.LoadFromStream(RequestStream);
    try
      ASuperObject:=SO(AStringStream.DataString);

      AIntfItem:=CommonRestServiceModule.IntfList.Find('datasets');
      if AIntfItem=nil then
      begin
        ADesc:='不存在datasets接口';
        Exit;
      end;

      //返回知识库列表
      AWhereKeyJsonArray:=SA();
      //ASuperObject中有两个参数，一个是parentId,表示父目录的ID，一个是searchKey表示搜索关键词
//      AWhereKeyJsonArray.O[AWhereKeyJsonArray.Length]:=GetFieldCondition('AND','parentId','=',ASuperObject.S['parentId']);
      // 如果searchKey不为空，则加上这个搜索条件，根据知识库的name和intro字段来过滤
      // if ASuperObject.S['searchKey']<>'' then
      // begin
      //   AWhereKeyJsonArray.O[AWhereKeyJsonArray.Length]:=GetFieldCondition('AND','name','like',ASuperObject.S['searchKey']);
      //   AWhereKeyJsonArray.O[AWhereKeyJsonArray.Length]:=GetFieldCondition('OR','intro','like',ASuperObject.S['searchKey']);
      // end;


      //查询记录
      if not AIntfItem.GetRecordList(AIntfItem.DBModule,
                                    nil,
                                    '',
                                    1,
                                    MaxInt,
                                    AWhereKeyJsonArray.AsJSON,
                                    '',
                                    '',0,0,'',0,
                                    ACode,
                                    ADesc,
                                    ADataJson,
                                    nil
                                    ) then
      begin
        Exit;
      end;


      Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;

    except
      on E:Exception do
      begin
        ADesc:=('RequestStream不是合法的Json格式');
        Result:=ReturnJson(ACode,ADesc,ADataJson).AsJSON;
        Exit;
      end;
    end;
  finally
    FreeAndNil(AStringStream);
  end;
end;


function TsrvRagCenterRestService.EchoString(const AString: String): String;
begin
  Result:='你好！'+astring;
end;




{ TRagCenterServiceModule }



constructor TRagCenterServiceModule.Create;
begin
  inherited;

end;

function TRagCenterServiceModule.CustomCopyConfigFromApp(
  ASQLDBHelper: TBaseDBHelper; ASourceAppID, ADestAppID: Integer;
  ADestAppJson: ISuperObject; var ADesc: String): Boolean;
//var
//  AUserListyJsonArray:ISuperArray;
//  AUserJson:ISuperObject;
//  I: Integer;
//  AUserFID:String;
begin
  Result:=False;
  try




      Result:=True;
  finally

  end;
end;

destructor TRagCenterServiceModule.Destroy;
begin

  inherited;
end;

procedure TRagCenterServiceModule.DoAfterStart;
begin
  inherited;


end;

function TRagCenterServiceModule.DoPrepareStart(var AError: String): Boolean;
var
  ACode:Integer;
  ADesc:String;
  ADataJson:ISuperObject;
begin
  Result:=Inherited DoPrepareStart(AError);

  GlobalRagServer:=TRagServer.Create(nil);
//  GlobalRagServer.FDBModule.DBConfigFileName:='RagCenterDBConfig.ini';
//  GlobalRagServer.FDBModule.DBConfig.FDBDataBaseName:='rag_center';
  GlobalRagServer.Start;



end;

function TRagCenterServiceModule.DoPrepareStop: Boolean;
begin

  GlobalRagServer.Stop;


  Result:=Inherited DoPrepareStop;


end;

//procedure TRagCenterServiceModule.Init;
//var
//  AIntfItem:TCommonRestIntfItem;
//  ADataFlowAction:TDataFlowAction;
//begin
//
//
//  {$REGION '知识库表'}
//  AIntfItem:=TCommonRestIntfItem.Create(
//    //名称
//    'datasets',
//    //名称
//    '知识库',
//    //数据库连接
//    RagCenterRestService.RagCenterServiceModule.DBModule,
//    //表名
//    'datasets',
//    '',
////    'SELECT * FROM ( '
////      +' SELECT '
////      +' A.*, '
////      +' B.name as introducer_name,B.phone as introducer_phone '
////      +' FROM tbluser A '
////      +' LEFT JOIN tbluser B ON A.appid=B.appid and B.fid=A.bind_introducer_fid '
////      +' ) view_user ',
//    '',
//    //删除字段
//    'is_deleted',
//    //主键字段
//    'fid',
//    //默认排序
//    'createtime DESC',
//    True);
//  CommonRestServiceModule.IntfList.Add(AIntfItem);
//  {$ENDREGION}
//
//
//
//  {$REGION '知识库数据集表'}
//  AIntfItem:=TCommonRestIntfItem.Create(
//    //名称
//    'dataset_collections',
//    //名称
//    '知识库数据集表',
//    //数据库连接
//    RagCenterRestService.RagCenterServiceModule.DBModule,
//    //表名
//    'dataset_collections',
//    '',
////    'SELECT * FROM ( '
////      +' SELECT '
////      +' A.*, '
////      +' B.name as introducer_name,B.phone as introducer_phone '
////      +' FROM tbluser A '
////      +' LEFT JOIN tbluser B ON A.appid=B.appid and B.fid=A.bind_introducer_fid '
////      +' ) view_user ',
//    '',
//    //删除字段
//    '',
//    //主键字段
//    '_id',
//    //默认排序
//    'createtime DESC',
//    True);
//  CommonRestServiceModule.IntfList.Add(AIntfItem);
//  {$ENDREGION}
//
//
//
//end;


initialization
  TkbmMWRTTI.EnableRTTI(TsrvRagCenterRestService);

  //服务模块
  RagCenterServiceModule:=TRagCenterServiceModule.Create();
  RagCenterServiceModule.DBModule.DBConfigFileName:='RagCenterDBConfig.ini';
  RagCenterServiceModule.DBModule.DBConfig.FDBDataBaseName:='rag_center';
  RagCenterServiceModule.Name:='知识库中心';
  RagCenterServiceModule.kbmMWCustomServiceClass:=TsrvRagCenterRestService;
  //注册
  RegisterServiceModule(RagCenterServiceModule);



finalization
  FreeAndNil(RagCenterServiceModule);


end.
