unit WebFileHttpService;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding 
// kbmMWCustomHTTPService to it. Eg.
// 
//     uses ...,kbmMWServer,kbmMWCustomHTTPService;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 
// 
// SPECIFIC HTTP SERVICE REGISTRATION INSTRUCTIONS
// -----------------------------------------------
// Cast the returned service definition object (sd) to a TkbmMWHTTPServiceDefinition. eg:
// 
// var
//    httpsd:TkbmMWHTTPServiceDefinition;
// ..
//    httpsd:=TkbmMWHTTPServiceDefinition(sd)
//    httpsd.RootPath[mwhfcHTML]:='webfiles/';
//    httpsd.RootPath[mwhfcImage]:='webfiles/images';
//    httpsd.RootPath[mwhfcJavascript]:='webfiles/js';
//    httpsd.RootPath[mwhfcStyleSheet]:='webfiles/css';
//    httpsd.RootPath[mwhfcOther]:='webfiles/files';
// -----------------------------------------------



{$I kbmMW.inc}

interface

uses
  SysUtils,
{$ifdef LEVEL6}
  Variants,
{$else}
  Forms,
{$endif}
  Classes,
  kbmMWSecurity,
  kbmMWServer,
  kbmMWServiceUtils,
  kbmMWGlobal,
  kbmMWFilePool,
  kbmMWCustomHTTPService;

type
  TkbmMWEventHTTPService2 = class(TkbmMWEventHTTPService)
  private
     { Private declarations }
  protected
     { Protected declarations }
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
    constructor Create(AOwner:TComponent);override;
  end;

var
  GlobalFilePool:TkbmMWFilePool;

implementation

uses kbmMWExceptions;

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TkbmMWEventHTTPService2.GetPrefServiceName:string;
begin
//     Result:='HTTPSERVICE';
  //要设置为空,不然用kbmMWHTTPSysServerTransport访问不到
  Result:='';
end;

constructor TkbmMWEventHTTPService2.Create(AOwner: TComponent);
begin
  inherited;
  FilePool:=GlobalFilePool;
end;

{$IFNDEF CPP}class{$ENDIF} function TkbmMWEventHTTPService2.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;


end.