//HAS_CCBARCODESCANNER;NO_GPSLOCATION;HAS_XIAOMIPUSH;HAS_HUAWEIPUSH;USE_NATIVE_SELECTMEDIA

//是否是客户端APP，还是商家端APP,还是员工端APP，决定用户角色和是否需要登录界面
{$DEFINE CLIENT_APP}

////是否需要定位
//{$DEFINE NO_GPSLOCATION}
//
////是否需要定位
//{$DEFINE HAS_GPSLOCATION}
//

//聊天
//{$DEFINE MULTIDEVICE}
//{$DEFINE MobileIMClient}


//是否需要微信支付
//{$DEFINE HAS_WXPAY}


//是否需要苹果登录
//{$DEFINE HAS_APPLESIGNIN}


//是否需要播放器
//{$DEFINE HAS_SUPERPLAYER}



//
////是否需要推送
//{$DEFINE HAS_PUSHNOTIFICATION}
////是否需要个推推送
//{$DEFINE HAS_GETUIPUSH}
//
//

////是否需要小米推送
//{$DEFINE HAS_XIAOMIPUSH}
////是否需要华为推送
//{$DEFINE HAS_HUAWEIPUSH}


//是否需要X5浏览器
//{$DEFINE HAS_X5WEBBROWSER}

//
////是否需要原生选择照片视频SDK
//{$DEFINE USE_NATIVE_SELECTMEDIA}
//
//
////是否需要百度OCR
//{$DEFINE HAS_CCBAIDU_OCR}
//
////是否需要二维码扫描
//{$DEFINE HAS_CCBARCODESCANNER}


//是否需要Facebook登录
//{$DEFINE HAS_FACEBOOK}



//需要自动升级
//{$DEFINE HAS_AUTOUPDATE}







